"""Generate the files and markup that make a site readable by search engines and AI assistants."""
from __future__ import annotations

import json
import re
import urllib.parse
from xml.sax.saxutils import escape

from . import aibots
from .crawl import Site


def robots_txt(origin: str, sitemap: str | None = None, block_training: bool = False) -> str:
    lines = [
        "# robots.txt generated by manar",
        "# Search engines and AI search/assistant crawlers are allowed, so AI answers can read and cite",
        "# this site.",
        "User-agent: *",
        "Allow: /",
    ]
    if block_training:
        lines += ["", "# AI training crawlers: blocked by policy (does not affect AI search answers)."]
        for bot in aibots.BOTS:
            if bot.kind == "training":
                lines += ["", f"User-agent: {bot.name}", "Disallow: /"]
    lines += ["", f"Sitemap: {sitemap or origin.rstrip('/') + '/sitemap.xml'}"]
    return "\n".join(lines) + "\n"


def sitemap_xml(urls: list[str]) -> str:
    body = "\n".join(f"  <url><loc>{escape(u)}</loc></url>" for u in dict.fromkeys(urls))
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + body + "\n</urlset>\n")


def llms_txt(name: str, summary: str, site: Site) -> str:
    """llms.txt (https://llmstxt.org): title, summary, then pages grouped by their first path segment."""
    groups: dict[str, list[str]] = {}
    for p in site.pages:
        if p.status >= 400 or "noindex" in p.meta.get("robots", "").lower():
            continue
        segment = urllib.parse.urlsplit(p.url).path.strip("/").split("/")[0] or "Overview"
        title = _plain(p.title) or p.url
        desc = _plain(p.meta.get("description", ""))
        groups.setdefault(segment.replace("-", " ").title(), []).append(
            f"- [{title}]({p.url})" + (f": {desc}" if desc else ""))
    parts = [f"# {name}", "", f"> {summary.strip()}"]
    for section in sorted(groups, key=lambda s: (s != "Overview", s)):
        parts += ["", f"## {section}", *groups[section]]
    return "\n".join(parts) + "\n"


def _clean(data: dict) -> dict:
    return {k: v for k, v in data.items() if v not in (None, "", [], {})}


def schema(kind: str, **f) -> dict:
    """JSON-LD for the entity types that matter most for being recognised and cited."""
    same_as = [s for s in (f.get("same_as") or []) if s]
    if kind == "organization":
        data = {"@type": "Organization", "name": f["name"], "url": f["url"], "logo": f.get("logo"),
                "description": f.get("description"), "sameAs": same_as}
    elif kind == "website":
        data = {"@type": "WebSite", "name": f["name"], "url": f["url"], "inLanguage": f.get("lang"),
                "description": f.get("description")}
    elif kind == "software":
        data = {"@type": "SoftwareApplication", "name": f["name"], "url": f["url"],
                "description": f.get("description"),
                "applicationCategory": f.get("category") or "DeveloperApplication",
                "operatingSystem": f.get("os") or "Windows, macOS, Linux",
                "softwareVersion": f.get("version"), "license": f.get("license"),
                "offers": {"@type": "Offer", "price": f.get("price", "0"),
                           "priceCurrency": f.get("currency", "USD")},
                "sameAs": same_as}
    elif kind == "sourcecode":
        data = {"@type": "SoftwareSourceCode", "name": f["name"], "codeRepository": f["url"],
                "description": f.get("description"), "programmingLanguage": f.get("language"),
                "license": f.get("license")}
    elif kind == "article":
        data = {"@type": "Article", "headline": f["name"], "url": f["url"],
                "description": f.get("description"),
                "datePublished": f.get("date"), "inLanguage": f.get("lang"),
                "author": {"@type": "Person", "name": f["author"]} if f.get("author") else None}
    else:
        raise ValueError("schema kind must be one of: organization, website, software, sourcecode, article")
    return {"@context": "https://schema.org", **_clean(data)}


def jsonld_script(data: dict) -> str:
    # "</" must not appear inside a script element: a value like "</script><script>..." would break out
    body = json.dumps(data, indent=2, ensure_ascii=False).replace("</", "<\\/")
    return '<script type="application/ld+json">\n' + body + "\n</script>"


def _plain(text: str) -> str:
    """Crawled text is untrusted: one line, no markdown link syntax, bounded length."""
    return re.sub(r"\s+", " ", text).replace("[", "(").replace("]", ")").strip()[:200]
